name: Execute Firebase Test

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin

      - name: Prepare Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase_credentials_raw.json
          # Ensure correct JSON formatting
          jq . firebase_credentials_raw.json > firebase_credentials.json
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          
      - name: List files and check credentials file content (Debugging purpose)
        run: |
          ls -lah
          cat firebase_credentials.json # Remove or comment this line in production to secure credentials

      - name: Run firebase_test.py
        run: python firebase_test.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '${{ github.workspace }}/firebase_credentials.json'
