name: Execute Firebase Test

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'  # Ensure this matches the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin

      - name: Prepare Firebase credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase_credentials.json
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Check created credentials file
        run: cat firebase_credentials.json

      - name: Run firebase_test.py
        run: python firebase_test.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: '${{ github.workspace }}/firebase_credentials.json'
