name: Execute Firebase Test

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin

      - name: Run firebase_test.py
        run: python firebase_test.py
